language: go

go:
  - 1.6
  - 1.7
  - 1.8

before_install:
  - go get -v github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
script:
  - golint ./...
  - go test -v ./...
  - gocov test | gocov report