name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.9, "1.10", 1.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Setup golint
      run: go get -v github.com/golang/lint/golint

    - name: Lint
      run: golint ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
